[platformio]
default_envs = nano33ble  ; Entorno por defecto

; ---------------------------------------------------
; ENTORNO 1: Arduino Nano 33 BLE (Maestro)
; ---------------------------------------------------
[env:nano33ble]
platform = nordicnrf52
board = nano33ble
framework = arduino
build_src_filter = +<maestro_nano.cpp>  ; Solo compila este archivo para la Nano

; ---------------------------------------------------
; ENTORNO 2: ESP32-S3 (Esclavo)
; ---------------------------------------------------
[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1             ; Ajusta el modelo exacto si es necesario
framework = arduino
build_src_filter = +<esclavo_esp32.cpp>  ; Solo compila este archivo para la ESP32