[platformio]
default_envs = nano33ble

; Configuración global
[env]
lib_deps = 
    arduino-libraries/Arduino_LSM9DS1 @ ^1.1.0
build_flags = 
    -Iinclude

[env:nano33ble]
platform = nordicnrf52
board = nano33ble
framework = arduino
build_src_filter = -<*> +<apartado_7/main_Nano.cpp>

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
build_src_filter = -<*> +<apartado_7/main_ESP32.cpp>
monitor_speed = 115200  ;