[platformio]
default_envs = nano33ble

[env:nano33ble]
platform = nordicnrf52
board = nano33ble
framework = arduino
build_src_filter = +<arduinoNano_I2C.cpp>
upload_port = COM3  ;
lib_deps = 
  arduino-libraries/Arduino_LSM9DS1 @ ^1.1.0

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
build_src_filter = +<esp32_I2C.cpp>